### ISSUE TITLE
Build using build-rr.sh fails

### ISSUE THREAD

**Issue by NiramayVaidya** [SEL4PROJ/rumprun#8]
The command I run is as follows-

`CC=<location_full_path>/rumprun/gcc9fix.sh SEL4_RROBJ=<location_full_path>/rumprun/obj-amd64-sel4 ./build-rr.sh sel4`

Note- before running the above command, I have already executed the init-sources.sh script to pull the submodules.

location_full_path is the full directory path where this rumprun repo has been cloned.

The gcc9fix.sh file contains the following-

`#!/bin/sh
gcc "$@" "-Wno-cast-function-type" "-Wno-tautological-compare" "-Wno-packed-not-aligned" "-Wno-uninitialized" "-Wno-address-of-packed-member" "-Wno-array-bounds"`

The output of this has been attached as a file. The issue observed here is as follows-

`<location_full_path>/rumprun/platform/sel4/pci/rumppci.c:13:10: fatal error: autoconf.h: No such file or directory
   13 | #include <autoconf.h>
      |          ^~~~~~~~~~~~`

Apart from the absence of this autoconf header, other header files like gen_config.h also seem to be missing. How can these issues be resolved?

Note- the reason why SEL4_RROBJ has been added when running build-rr.sh is because if this is not included, I get an error at line 85 in-

`<location_full_path>/rumprun/platform/sel4/Makefile`

I am wondering whether the way I am trying to build this is correct to begin with (i.e. by directly running build-rr.sh as above). I have successfully been able to build different demo-apps in the https://github.com/seL4/rumprun-sel4-demoapps repo using the ninja and cmake build framework being used there. Though, since the demo-apps repo essentially uses this same seL4 rumprun repo (https://github.com/seL4/rumprun), I wanted to check if I can build this repo directly too.
I see that the demo-apps repo has multiple other components like the kernel directory and other directories under the projects folder (apart from this rumprun directory). I believe all these components together are required to successfully build the demo-apps repo to run different apps. Is there any way the same outcome can be achieved in this repo?

[compile_output_1.txt](https://github.com/seL4/rumprun/files/10984058/compile_output_1.txt)

**Comment by kent-mcleod** [comment]
Hi, a recent upstream change to the kernel config build rules mean that the gen_config.h and autoconf.h files are now generated as a ninja build command. [This recent PR](https://github.com/seL4/rumprun/pull/7/files)  added build dependencies to the build-rr.sh commands that should already ensure that the header files are generated before build-rr.sh is invoked.

**Comment by NiramayVaidya** [comment]
Thanks! Pulling the commit from this PR helped.
